# Generated by Django 3.2.5 on 2021-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='GW ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='GW Name')),
                ('deadline_time', models.DateTimeField(verbose_name='Deadline Time')),
                ('deadline_time_epoch', models.IntegerField(verbose_name='Epoch Time')),
            ],
            options={
                'verbose_name': 'Fixture Date',
                'verbose_name_plural': 'Fixture Dates',
            },
        ),
    ]
