# Generated by Django 3.2.5 on 2021-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0002_auto_20210801_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammeta',
            options={'verbose_name': 'EPL Team', 'verbose_name_plural': 'EPL Teams'},
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='GW Completed'),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='end_time',
            field=models.PositiveBigIntegerField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Is Current GW'),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='start_time',
            field=models.PositiveBigIntegerField(verbose_name='Start Time'),
        ),
    ]
