# Generated by Django 3.2.5 on 2021-08-08 11:01

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0003_auto_20210802_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('team', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fplservice.teammeta', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Footballer',
                'verbose_name_plural': 'Footballers',
            },
        ),
        migrations.CreateModel(
            name='FootballerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(verbose_name='GW Minutes')),
                ('points', models.IntegerField(verbose_name='GW Points')),
                ('total_selection', models.IntegerField(verbose_name='GW Selections')),
                ('footballer', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fplservice.footballer', verbose_name='Footballer')),
                ('gw', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fplservice.gameweek', verbose_name='Footballer')),
            ],
            options={
                'verbose_name': 'Footballer GW Performance',
            },
        ),
    ]
