# Generated by Django 3.2.5 on 2021-08-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0004_footballer_footballerperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='assists'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballer',
            name='clean_sheets',
            field=models.IntegerField(default=0, verbose_name='clean_sheets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballer',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballer',
            name='goals_conceded',
            field=models.IntegerField(default=0, verbose_name='goals_conceded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballer',
            name='goals_scored',
            field=models.IntegerField(default=0, verbose_name='goals_scored'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballer',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='red_cards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballer',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='yellow_cards'),
            preserve_default=False,
        ),
    ]
