# Generated by Django 3.2.5 on 2021-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0005_auto_20210809_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='assists'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='clean_sheets',
            field=models.IntegerField(default=0, verbose_name='clean_sheets'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='goals_conceded',
            field=models.IntegerField(default=0, verbose_name='goals_conceded'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='goals_scored',
            field=models.IntegerField(default=0, verbose_name='goals_scored'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='red_cards'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='yellow_cards'),
        ),
    ]
