# Generated by Django 3.2.5 on 2021-08-09 17:13

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fplservice", "0006_auto_20210809_2244"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                ("name", models.IntegerField(unique=True, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Positions",
            },
        ),
    ]
