# Generated by Django 3.2.5 on 2021-08-09 17:22

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0008_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='position',
            field=auto_prefetch.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fplservice.position', verbose_name='Position'),
            preserve_default=False,
        ),
    ]
