# Generated by Django 3.2.5 on 2021-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0011_auto_20210812_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='last_stats_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Stats Updated Time'),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='stats_completed',
            field=models.BooleanField(default=False, verbose_name='Stats Completed'),
        ),
    ]
