# Generated by Django 3.2.5 on 2021-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0012_auto_20210812_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='form_5_gw',
            field=models.FloatField(default=0, verbose_name='Form (5 GW)'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='form_season',
            field=models.FloatField(default=0, verbose_name='Form (Season)'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='points_per_mil_5_gw',
            field=models.FloatField(default=0, verbose_name='Points Per Million (5 GW)'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='points_per_mil_season',
            field=models.FloatField(default=0, verbose_name='Points Per Million (Season)'),
        ),
    ]
