# Generated by Django 3.2.5 on 2021-08-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0014_auto_20210814_0218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footballerperformance',
            unique_together={('footballer', 'gw')},
        ),
    ]
