# Generated by Django 3.2.5 on 2022-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0015_alter_footballerperformance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='active_gameweek',
            field=models.BooleanField(default=True, verbose_name='Active Gameweek'),
        ),
    ]
