# Generated by Django 3.2.5 on 2021-08-01 11:42

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Team Id')),
                ('team_name', models.CharField(max_length=50, verbose_name='Team Name')),
                ('manager_id', models.IntegerField(unique=True, verbose_name='Manager Id')),
                ('manager_name', models.CharField(max_length=50, verbose_name='Manager Name')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw', models.IntegerField(verbose_name='Gameweek')),
                ('team_value', models.IntegerField(verbose_name='Team Value')),
                ('transfers', models.IntegerField(verbose_name='Transfers')),
                ('transfers_hits', models.IntegerField(verbose_name='Transfer Hits')),
                ('chip', models.CharField(max_length=10, verbose_name='Chip')),
                ('last_gw', models.IntegerField(verbose_name='Last GW')),
                ('site_pts', models.IntegerField(verbose_name='Site Points')),
                ('cvc_pens', models.IntegerField(verbose_name='Captain/VC Penalty')),
                ('inactive_players', models.IntegerField(verbose_name='Inactive Players')),
                ('gw_points', models.IntegerField(verbose_name='GW Points (+Pens)')),
                ('rank', models.IntegerField(verbose_name='GW Rank')),
                ('last_rank', models.IntegerField(verbose_name='Last GW Rank')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('manager', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifpl.manager', verbose_name='manager')),
            ],
            options={
                'verbose_name': 'Points Table',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
