# Generated by Django 3.2.5 on 2021-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifpl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstable',
            name='site_pts',
        ),
        migrations.AddField(
            model_name='pointstable',
            name='inactive_players_pens',
            field=models.IntegerField(null=True, verbose_name='Inactive Players Penalty'),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='itb',
            field=models.IntegerField(default=0, verbose_name='In the Bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointstable',
            name='site_points',
            field=models.IntegerField(default=0, verbose_name='Site Points'),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='chip',
            field=models.CharField(max_length=10, null=True, verbose_name='Chip'),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='cvc_pens',
            field=models.IntegerField(null=True, verbose_name='Captain/VC Penalty'),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='gw_points',
            field=models.IntegerField(default=0, verbose_name='GW Points (+Pens)'),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='inactive_players',
            field=models.IntegerField(null=True, verbose_name='Inactive Players'),
        ),
    ]
