# Generated by Django 3.2.5 on 2021-08-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fplservice', '0004_footballer_footballerperformance'),
        ('antifpl', '0002_auto_20210802_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballerPerformanceAnti',
            fields=[
                ('footballerperformance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fplservice.footballerperformance')),
                ('anti_points', models.IntegerField(verbose_name='Anti Points')),
            ],
            options={
                'verbose_name': "Footballer's Performance Anti",
            },
            bases=('fplservice.footballerperformance',),
        ),
    ]
