# Generated by Django 3.2.5 on 2021-08-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antifpl', '0004_alter_pointstable_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footballerperformanceanti',
            options={'verbose_name': "Footballer's Performance Anti", 'verbose_name_plural': 'Footballer Performance Anti'},
        ),
    ]
