# Generated by Django 3.2.5 on 2021-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifpl', '0005_alter_footballerperformanceanti_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballerperformanceanti',
            name='anti_points',
            field=models.IntegerField(default=0, verbose_name='Anti Points'),
        ),
    ]
