# Generated by Django 3.2.5 on 2021-08-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifpl', '0006_alter_footballerperformanceanti_anti_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballerperformanceanti',
            name='anti_points',
            field=models.IntegerField(default=0, null=True, verbose_name='Anti Points'),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='last_gw',
            field=models.IntegerField(verbose_name='Last GW Points'),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='rank',
            field=models.IntegerField(null=True, verbose_name='GW Rank'),
        ),
    ]
