# Generated by Django 3.2.5 on 2022-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifpl', '0008_auto_20210814_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstable',
            name='chip_pen',
            field=models.IntegerField(null=True, verbose_name='Chip Penalty'),
        ),
    ]
